version: '2'
services:
  # Cerebro Elasticsearch client
  cerebro:
    image: yannart/cerebro:latest

    ports:
      - "9000:9000"
    networks:
      - app_net

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: kd2017_elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    memswap_limit: 0
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
